spring:
  data:
    elasticsearch:
      cluster-name: raymond-es-cls
      cluster-nodes: 182.254.138.59:9300
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://182.254.138.59:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: Raymond888@qq.com
server:
  port: 8033