server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://182.254.138.59:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    password: Raymond888@qq.com
  redis:
    database: 0
    host: 182.254.138.59
    port: 6379
    password: Raymond888@qq.com

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl      # 开启控制台打印sql日志 不要在生产环境使用
